apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nginx
type: Opaque
data:
 mysql-root-password: cm9vdDEyMzQ1
 mysql-user: YWRtaW4=
 mysql-password: cm9vdDEyMzQ1
 mysql-host: ZGF0YWJhc2UtMS5jNTBlcWkwYzJlZzMuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==


